version: "3.9"

services:
  app:
    build: .
    container_name: sleep-tracker-be
    env_file:
      - .env.docker
    ports:
      - "9000:3000"
    depends_on:
      - db
      - redis
    networks:
      - appnet
    volumes:
      - .:/usr/src/ruby-boilerplate:cached

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet:
    driver: bridge
