development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: <%= ENV.fetch("APP_NAME") { "ruby-boilerplate-be" } %>_production
