default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 10 } %>
  timeout: <%= ENV.fetch("DB_TIMEOUT") { 20000 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "sleep_tracker_development" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "sleep_tracker_test" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

production:
  adapter: postgresql_makara
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 10 } %>
  timeout: <%= ENV.fetch("DB_TIMEOUT") { 20000 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>
  makara:
    id: postgres_cluster
    sticky: true
    connections:
      - role: master
        host: <%= ENV.fetch("DB_HOST") { "db" } %>
        port: <%= ENV.fetch("DB_PORT") { 5432 } %>
        name: primary
      - role: slave
        host: <%= ENV.fetch("DB_REPLICA_HOST") { "db" } %>
        port: <%= ENV.fetch("DB_PORT") { 5432 } %>
        name: replica
