development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
  options:

test:
  clients:
    default:
      database: dci_middleware_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: <%= ENV['MONGODB_TIME_OUT'] || 15 %>
        wait_queue_timeout: <%= ENV['MONGODB_WAIT_TIME_OUT'] || 15 %>
        min_pool_size: <%= ENV['MONGODB_MIN_POOL_SIZE'] || 5 %>
        max_pool_size: <%= ENV['MONGODB_MAX_POOL_SIZE'] || 10 %>
  options: