# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "sli"

development:
  <<: *common
  brokers:
    - <%= ENV['KAFKA_SERVER'] %>
  group_id:
    - <%= ENV['KAFKA_GROUP_ID'] %>
  group_id_prefix:
    - <%= ENV['KAFKA_GROUP_ID_PREFIX'] %>

test:
  <<: *common
  brokers:
    - localhost:9092

production:
  <<: *common
  brokers:
    - <%= ENV['KAFKA_SERVER'] %>
  group_id:
    - <%= ENV['KAFKA_GROUP_ID'] %>
  group_id_prefix:
    - <%= ENV['KAFKA_GROUP_ID_PREFIX'] %>
